export default {
  javascript: {
    category: "skill",
    title: "JavaScript",
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    img: "/images/javascript.webp",
    level: 4,
    content: `Running on browsers, running server side now with {nodejs}. A very versatile and well supported language.`,
    tags: ["languages", "javascript"],
  },
  vuejs: {
    category: "skill",
    title: "VueJS",
    link: "https://vuejs.org/",
    img: "/images/vuejs.webp",
    content:
      "{vuejs} is my favorite javascript framework. It is simple, and yet fully featured. I recommend it in all my new projects that do not require a very specific set of dependencies. We use it for the front end of the {microlearning} application and the {naas} {moodle} plugin.",
    level: 4,
    tags: ["javascript", "frameworks"],
  },
  java: {
    category: "skill",
    title: "Java",
    img: "/images/java.webp",
    link: "https://www.java.com/",
    content:
      "The old classic. We are using it for the {naas} webservices with {vertx}. I also used it at {quadran} for the {appyuser} application.",
    level: 3,
    tags: ["java", "languages"],
  },
  vertx: {
    category: "skill",
    title: "Vert.x",
    img: "/images/vertx.webp",
    link: "https://vertx.io/",
    level: 3,
    content:
      "A very good {java} event driven framework. It empowers the developer with the ability to control how threads are spawned and thus optimize application resource consumption. I chose it in the {naas} architecture to make sure we could scale to the fullest.",
    tags: ["java", "frameworks"],
  },
  drupal: {
    category: "skill",
    title: "Drupal",
    link: "https://www.drupal.org/",
    img: "/images/drupal.webp",
    level: 3,
    content:
      "A content management system written in {php} which helped us speed up considerably the development of the {naas} content editor.",
    tags: ["php", "cms"],
  },
  php: {
    category: "skill",
    title: "PHP",
    link: "https://www.php.net/",
    img: "/images/php.webp",
    level: 3,
    content: `{php} is considered by many as an abomination. 
      I think it has come a long way with class based development and next gen frameworks such as {laravel} and CMSs like {drupal}... I use it for the {naas} content editor and {moodle} plugin projects.`,
    tags: ["php", "languages"],
  },
  moodle: {
    category: "skill",
    title: "Moodle",
    link: "https://moodle.com/",
    img: "/images/moodle.webp",
    level: 3,
    content: `Moodle is the learning management system used at {isae-supaero}. I developed two modules for this application, a reporting tool called {hybridmeter} and a content viewer for {naas} hosted resources.`,
    tags: ["php", "cms"],
  },
  nuxeo: {
    category: "skill",
    title: "Nuxeo",
    link: "https://doc.nuxeo.com/",
    img: "/images/nuxeo.webp",
    level: 3,
    content: `Nuxeo is a very powerful document management system we use for the {naas} project as a technical layer thanks to its comprehensive API.`,
    tags: ["java", "cms"],
  },
  elasticsearch: {
    category: "skill",
    title: "Elasticsearch",
    link: "https://www.elastic.co/",
    img: "/images/elasticsearch.webp",
    level: 3,
    content: `A highly and easily scalable noSQL database backed by {lucene} which is very efficient for fulltext search for instance. I used it in the {naas} and {appyuser} projects. In particular I wrote {python} scripts to migrate data to {elasticsearch} from multiple sources like {traxlrs} or SQL databases.`,
    tags: ["databases"],
  },
  traxlrs: {
    category: "skill",
    title: "TraxLRS",
    link: "https://traxlrs.com/",
    img: "/images/traxlrs.webp",
    level: 4,
    content: `A fully compliant {xapi} server we use to store learning traces for the {naas} platform.`,
    tags: ["tools"],
  },
  jenkins: {
    category: "skill",
    title: "Jenkins",
    link: "https://www.jenkins.io/",
    img: "/images/jenkins.webp",
    level: 3,
    content: `A CI/CD tool  I use since 2015 on all my projects with integration with {gitlab}, {github} and most recently {sonarqube}`,
    tags: ["tools"],
  },
  sonarqube: {
    category: "skill",
    title: "Sonarqube",
    link: "https://www.sonarqube.org/",
    img: "/images/sonarqube.webp",
    level: 2,
    content: `Code quality analysis tool. I started using Sonarqube very recently to statically analyse the code for the {naas} and run unit tests.`,
    tags: ["tools"],
  },
  oracle: {
    category: "skill",
    title: "Oracle",
    link: "https://www.oracle.com/",
    img: "/images/oracle.webp",
    level: 3,
    content: `Good old database. I used Oracle in most projects between 2015 and 2019 as it was {isae-supaero} main database system. I also followed an Oracle 11G database training course.`,
    tags: ["databases"],
  },
  postgresql: {
    category: "skill",
    title: "PostgreSQL",
    link: "https://www.postgresql.org/",
    img: "/images/postgresql.webp",
    level: 3,
    content: `My go to production grade SQL database if I have no constraints.`,
    tags: ["databases"],
  },
  ldap: {
    category: "skill",
    title: "LDAP",
    link: "https://www.openldap.org/",
    img: "/images/openldap.webp",
    level: 3,
    content: `An open source directory. I integrated many applications with openLDAP at {isae-supaero}. I also deployed and configured an instance of openLDAP as part of an integration project related to the {naas} `,
    tags: ["databases"],
  },
  python: {
    category: "skill",
    title: "Python",
    link: "https://www.python.org/",
    img: "/images/python.webp",
    level: 4,
    content: `My favorite server side language. Scripting, Web applications, Native applications. good at everything except time and performance critical applications. I know that some people do not like {duck_typing} though.`,
    tags: ["languages", "python"],
  },
  ruby: {
    category: "skill",
    title: "Ruby",
    link: "https://www.ruby-lang.org/",
    img: "/images/ruby.webp",
    level: 1,
    content: `I did not code a lot in ruby, but I appreciated the powerful monkey patching features.`,
    tags: ["languages", "ruby"],
  },
  rails: {
    category: "skill",
    title: "Ruby on Rails",
    link: "https://rubyonrails.org/",
    img: "/images/rails.webp",
    level: 1,
    content: `The {redmine} project was not long enough to get me opinionated about {rails}. But I am left with good memories.`,
    tags: ["ruby", "frameworks"],
  },
  "c++": {
    category: "skill",
    title: "C++",
    link: "https://cplusplus.com/",
    img: "/images/c++.webp",
    level: 1,
    content: `This is a long time ago! I supposed the patterns changed since I was coding {opengl} games in C++.`,
    tags: ["languages"],
  },
  nodejs: {
    category: "skill",
    title: "NodeJS",
    link: "https://nodejs.org/en/",
    img: "/images/nodejs.webp",
    level: 2,
    content: `{nodejs} is 'just' a javascript runtime environment for server. I shamelessly gave training on {nodejs} and {express} without using it professionally.`,
    tags: ["javascript"],
  },
  angular: {
    category: "skill",
    title: "Angular",
    link: "https://angular.dev/",
    img: "/images/angular.webp",
    level: 2,
    content: `JavaScript framework. Angular 1 (AngularJS) was great. It was my first experience with a reactive JavaScript framework and I used it in the {appyuser} project. I used Angular 2 in the {cosinus} project and was disappointed. It is powerful, yet, it made things difficult for no reason.`,
    tags: ["javascript", "frameworks"],
  },
  spring: {
    category: "skill",
    title: "Spring",
    link: "https://spring.io/projects/spring-framework/",
    img: "/images/spring.webp",
    level: 2,
    content: `Web server framework. I do not have a lot of experience with {spring}. When I used it in the {litiges} project, I found it bloated. Nevertheless I took a look at the Spring express when I was designing the {naas} architecture and it looks like a decent iteration.`,
    tags: ["java", "frameworks"],
  },
  react: {
    category: "skill",
    title: "ReactJS",
    link: "https://react.dev/",
    img: "/images/react.webp",
    level: 4,
    content: `A very decent web framework. I started using React in 2021 with the {web3} projects in 2021. I think it suffers from its long history but it is still very convenient. It is also very powerful with Server Side Rendering frameworks like {nextjs}`,
    tags: ["javascript", "frameworks"],
  },
  nextjs: {
    category: "skill",
    title: "NextJS",
    link: "https://nextjs.org/",
    img: "/images/nextjs.webp",
    level: 4,
    content: `A server side rendering framework based on {react}. The last {web3} project I am working on is based on {nextjs}. Once again I discovered I knew nothing. Great development experience.`,
    tags: ["javascript", "frameworks"],
  },
  bash: {
    category: "skill",
    title: "Bash",
    link: "https://en.wikipedia.org/wiki/Bash_(Unix_shell)",
    img: "/images/bash.webp",
    level: 4,
    content: `Linux shell. I made a lot of {bash} scripts for continuous deployment, database dumping and restoration, filesystem backing up and so on since 2015.`,
    tags: ["system", "languages"],
  },
  kubernetes: {
    category: "skill",
    title: "Kubernetes",
    link: "https://kubernetes.io",
    img: "/images/kubernetes.webp",
    level: 3,
    content: `I deployed a privately hosted production grade Kubernetes cluster for the {naas} project using {kubespray}, {calico}, {prometheus} and {nginx_ingress}`,
    tags: ["system"],
  },
  apache: {
    category: "skill",
    title: "Apache",
    link: "https://httpd.apache.org/",
    img: "/images/apache.webp",
    level: 3,
    content: `I deployed Apache in many contexts. As a webserver, reverse proxy or WSGI server.`,
    tags: ["system"],
  },
  nginx: {
    category: "skill",
    title: "Nginx",
    link: "https://nginx.org/",
    img: "/images/nginx.webp",
    level: 3,
    content: `These last years I used nginx over apache given the nice performance reviews. I made some deployments mostly as a webserver or reverse proxy for the {naas} {kubernetes} cluster.`,
    tags: ["system"],
  },
  django: {
    category: "skill",
    title: "Django",
    link: "https://www.djangoproject.com/",
    img: "/images/django.webp",
    level: 4,
    content: `I usually use Django for backend servers. I used it for the {microlearning} server for instance. I also coupled it with {django-rest}. For smaller projects {flask} is good though.`,
    tags: ["python", "frameworks"],
  },
  solidity: {
    category: "skill",
    title: "Solidity",
    link: "https://soliditylang.org/",
    img: "/images/solidity.webp",
    level: 3,
    content: `The main language for smart contracts on Ethereum-compatible chains. I used {solidity} to implement the blockchain infrastructure of the {carbonmark} marketplace.`,
    tags: ["languages", "web3"],
  },
  viem: {
    category: "skill",
    title: "Viem",
    link: "https://viem.sh/",
    img: "/images/viem.webp",
    level: 3,
    content: `A typescript library for interacting with Ethereum. I used {viem} in the {carbonmark} frontend to read and write smart contracts from the browser.`,
    tags: ["javascript", "web3"],
  },
  fastify: {
    category: "skill",
    title: "Fastify",
    link: "https://fastify.dev/",
    img: "/images/fastify.webp",
    level: 4,
    content: `A high performance {nodejs} web framework. I designed the {carbonmark} backend architecture with {fastify}.`,
    tags: ["javascript", "frameworks"],
  },
  circle: {
    category: "skill",
    title: "Circle",
    link: "https://www.circle.com/",
    img: "/images/circle.webp",
    level: 3,
    content: `Circle provides wallet abstraction and USDC payment infrastructure. I integrated it in the {carbonmark} marketplace to simplify onchain wallet management for end users.`,
    tags: ["tools", "web3"],
  },
  stripe: {
    category: "skill",
    title: "Stripe",
    link: "https://stripe.com/",
    img: "/images/stripe.webp",
    level: 3,
    content: `Payment processing platform. I integrated {stripe} into {carbonmark} to handle fiat payments alongside the blockchain flows.`,
    tags: ["tools"],
  },
};
